/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class task4_NativeMatrix */

#ifndef _Included_task4_NativeMatrix
#define _Included_task4_NativeMatrix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     task4_NativeMatrix
 * Method:    allocateNativeMatrix
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_task4_NativeMatrix_allocateNativeMatrix
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     task4_NativeMatrix
 * Method:    overrideNativeMatrix
 * Signature: ([[I)J
 */
JNIEXPORT jlong JNICALL Java_task4_NativeMatrix_overrideNativeMatrix
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     task4_NativeMatrix
 * Method:    freeNativeMatrix
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_task4_NativeMatrix_freeNativeMatrix
  (JNIEnv *, jobject, jlong);

/*
 * Class:     task4_NativeMatrix
 * Method:    mult
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_task4_NativeMatrix_mult
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     task4_NativeMatrix
 * Method:    values
 * Signature: (J)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_task4_NativeMatrix_values
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
